### ISSUE TITLE
Injection SQL

### ISSUE THREAD

**Issue by EnseignantLapro** [Tellier-Neo/Projet-E#1]
Sur l'appel de l'api j'ai fais une injection SQL de ce type : 

{
    "identifiant": "coucou\;select * from toto",
    "password": null
}

**Comment by EnseignantLapro** [comment]
l'antislache est aprés le 2ieme u de coucou et le ;

**Comment by Tellier-Neo** [comment]
Le problème est réglé, le serveur effectue maintenant une vérification de la structure du JSON afin de voir s'il est valide ou non et ignore dans le cas ou le JSON reçu est invalide
